I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/episodes/episode6.rpy", line 305, in script
    with glitch
TypeError: __init__() missing 1 required positional argument: 'child'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/episodes/episode6.rpy", line 305, in script
    with glitch
  File "D:\Programming\RenPy\renpy-8.0.3-sdk\renpy\ast.py", line 1658, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "D:\Programming\RenPy\renpy-8.0.3-sdk\renpy\exports.py", line 1657, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "D:\Programming\RenPy\renpy-8.0.3-sdk\renpy\display\core.py", line 2798, in do_with
    return self.interact(trans_pause=True,
  File "D:\Programming\RenPy\renpy-8.0.3-sdk\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\Programming\RenPy\renpy-8.0.3-sdk\renpy\display\core.py", line 3752, in interact_core
    trans = self.ongoing_transition[None](
TypeError: __init__() missing 1 required positional argument: 'child'

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
ERAIDAproject 6.0
Fri Dec 30 05:55:08 2022
